name: pr-policy
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  linked-issue:
    name: Linked issue
    runs-on: ubuntu-latest
    steps:
      - uses: husterk/.github/actions/linked-issue@0993d62dd63db07836c904534f09a368d2ffa9f3 # v2.0.0
